services:

  n8n:
    image: ${N8N_IMAGE}
    container_name: n8n
    restart: always
    env_file:
      - ./.env
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=${DB_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - web
      - db_net

  cloudflared:
    image: ${CLOUDFLARED_IMAGE}
    container_name: cloudflared
    env_file:
      - ./.env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command:
      - "tunnel"
      - "run"
      - "--url"
      - "${N8N_INTERNAL_URL}"
    restart: always
    networks:
      - web

  postgres:
    image: ${POSTGRES_IMAGE} # Fixado na versão 18 compatível com o banco existente
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - db_net

networks:
  web:
    external: false
  db_net:
    external: false
